### ISSUE TITLE
Chemins d'import CSS non compilés

### ISSUE THREAD

**Issue by narduin** [datagouv/udata-front#499]
Bonjour,

Je travaille sur [`u-data-front-kit`](https://github.com/opendatateam/udata-front-kit/tree/main) et je rencontre un petit problème.
En utilisant le composant [`DsfrBadge`](https://vue-ds.fr/composants/DsfrBadge) avec une icône, cette dernière est appelée ici: `url(../../icons/system/fr--info-fill.svg)`

Via `@gouvfr/dsfr`, le chemin est compilé:

- `url(/node_modules/@gouvfr/dsfr/dist/icons/system/fr--info-fill.svg)` en dev
- `url(/assets/fr--info-fill.svg)` en prod

Cependant, avec `@datagouv/component` la règle CSS est préfixée par `.datagouv-components` et le chemin reste inchangé (en dev ou en prod) ce qui donne une 404.

J'ai testé directement avec le repo `datagouv-components` en ajoutant un badge
```html
<p class="fr-badge fr-badge--info">info</p>
```
et le résultat est le même.

Merci !

**Comment by nicolaskempf57** [comment]
Merci du retour, effectivement ce n'est pas normal qu'on inclut du code du DSFR. Je prépare un fix.
